### ISSUE TITLE
Can't add slashes in Open with left-clic list

### ISSUE THREAD

**Issue by lupinpv** [andy-portmen/open-in#1]
I need to add slashes in then Open with right-clic list because I need all file:/// links to open in IE (to open folders in windows explorer). But slashes are not saved. You also can't specify domain folder like www.example.com/Folder/

**Comment by andy-portmen** [comment]
Okay makes sense. I added a new list to allow URL insertion as well. You can test it in the dev version.

**Comment by lupinpv** [comment]
Thank you, it seems great. Sorry for this question but how can I get the dev version ?

**Comment by andy-portmen** [comment]
Try my "Open in Firefox". It is the only "Open In" extension that has the option for now. Let me know if it works as expected.
