### ISSUE TITLE
Open in Vivaldi Firefox add-on not working.

### ISSUE THREAD

**Issue by mrplumber** [andy-portmen/open-in#11]
Hi,

Using Open in Vivaldi addon for Firefox (latest release version) on Windows 10 x64. Unfortunately hasn't been working for a while. On button press, console window pops up for a very short moment, then closes and nothing else happens. Tried Open in Internet Explorer with same result.

Also using Open in Firefox addon for Vivaldi. Works fine.

**Comment by andy-portmen** [comment]
Sorry for the late reply! Can you double check the browser console (Ctrl + Shift + J) and see if you get an error when the button is pressed?

**Comment by mrplumber** [comment]
Nothing happens in browser console when I press the button.

**Comment by andy-portmen** [comment]
I just released a new version. Go to the options page and press the reset button once. Let me know if the issue is fixed.

**Comment by andy-portmen** [comment]
Great! 

Firefox's native messaging API is a mess on Windows OS. Basically, for all Chromium browsers, I use `cmd /s/c start browser_name URL` to open and detach the console so I could release the backend NodeJS executable when the browser is launched. In FF, NodeJS is executed as a child process and hence if it gets closed, the destination browser itself also get closed! so I need to use something like `cmd /s/c start /WAIT browser_name URL` instead. I guess that's the reason why you get the console for a short period.
