### ISSUE TITLE
Open-in-chrome works with vivaldi?

### ISSUE THREAD

**Issue by Hadden89** [andy-portmen/open-in#12]
I'm trying to setup the open-in-chrome on Vivaldi but it fails.
I resume the step I did -- hoping is not a bug or my fault somewhere.

1) Installed the native client as user (readme says it doesn't need admin anymore); no errors in the batch;
2) Merged open-in-chrome and common folder from the repo.
Symlinks seems to fails on windows, so I had to manually populate the extension folder. (a crx version would be nice to have it "prepacked").
3) Load the extension as unpacked -- extension page says "Unrecognized manifest key 'applications'"
4) Put my chrome beta path in settings, but seems not to be working.
I remember there was an open with in context menu. I don't see it.

Tried also open-in-firefox (from chrome store) and it worked, so I guess native client is correctly installed.

**Comment by andy-portmen** [comment]
If the FF version works it means the native client is installed successfully. The only thing you missed is the extension id. In the FF version, extension id is forced so the native client can find the extension. For Chrome copy the extension id from the extensions manager and add it into https://github.com/andy-portmen/native-client/blob/master/config.js

Let me know if it worked
