### ISSUE TITLE
Confusion over updates

### ISSUE THREAD

**Issue by TheCalrissian** [andy-portmen/open-in#14]
Hello, I'm using "Open In VLC" version 0.1.5 on Chrome for MacOS. 

However, on the app's webpage, [https://add0n.com/open-in.html] the version is listed as 0.2.2 (see attached screen grab).

Is there an update to the app or does 0.2.2 refer to something else because I can't locate the update? Thank you!

<img width="749" alt="screen shot 2018-09-13 at 9 30 29 pm" src="https://user-images.githubusercontent.com/43256866/45524571-13848300-b79d-11e8-95af-fa99f406bad1.png">

Sincerely,
Brando Calrissian

**Comment by andy-portmen** [comment]
This version is for another open-in add-on in the same FAQ page. Yours is the current version.

**Comment by TheCalrissian** [comment]
Thank you!
