### ISSUE TITLE
Left-click doesn't work. Help please

### ISSUE THREAD

**Issue by maxirk** [andy-portmen/open-in#16]
Open With Keyboard-Mouse-Click Combinations doesn't work. I enabled all https://tao38.ru/_myfiles/openinchrome.jpg but doesn't work. How to make shortcuts work?
The add-on only works via context menu.

Firefox 60.3.0esr (64-бит) and Chrome 70.0.3538.77

**Comment by andy-portmen** [comment]
Unfortunately not all combinations work in all browsers. You need to play with different combinations. Make sure to refresh the page for the changes to apply.
