### ISSUE TITLE
Feature req: The "Open with left click" list option needs a wildcard

### ISSUE THREAD

**Issue by the-moog** [andy-portmen/open-in#18]
The open with left click needs support for wildcard domains.
e.g.
Rather than requiring all of "server1.domain.com, host2.domain.com, www.domain.com, domain.com" to be in the list, we should be able to supply either just domain.com or *.domain.com (or perhaps both for more flexability)

**Comment by andy-portmen** [comment]
If you add `domain.com`, the domain itself and all subdomains are being considered.
