### ISSUE TITLE
Open In Chrome incognito mode possible?

### ISSUE THREAD

**Issue by jskang-netex** [andy-portmen/open-in#19]
This extension has been very useful for me. I'm using Open In with Firefox v63.0.3 on Win10 Pro.  

I was wondering if it's possible to have the Open In Chrome extension open Chrome in Incognito mode. Is it as simple as just adding the "-incognito" flag to the path to the executable field?

I searched here but didn't come up with any other posts that seemed to match the question that I have.

Thanks in advance.

**Comment by andy-portmen** [comment]
Since the open-in's add-ons do not accept command line arguments, the easiest way is to create a batch script and call the destination browser from the batch script. Now point the extension in the options page to this batch script. It will get called with the URL as the input argument.

**Comment by andy-portmen** [comment]
another options is to use my external application button extension which does support command line arguments.

**Comment by e-t-l** [comment]
>  the open-in's add-ons do not accept command line arguments

@andy-portmen has this changed? Since multiple versions of the addon, e.g. open in Firefox and Chromium, have a list of command line switches for those apps. It seems weird that you would include cmd arguments if they couldn't be used...
