### ISSUE TITLE
https and GIMP

### ISSUE THREAD

**Issue by wd5gnr** [andy-portmen/open-in#21]
Not very useful for GIMP since -- at least on my install -- I can't do an Open location on https (http works fine). But with so many sites now forcing you to https (and yes I disabled https anywhere as a test) that means good chance GIMP won't open the file but just give you an error. In addition, it seems like it was choking in a different way if there was something after the .jpg (or whatever) extension in the URL (like http://foo.bar/x.jpg?bettanote=1

**Comment by andy-portmen** [comment]
there is an option to download the file to the local disk first.
