### ISSUE TITLE
Add URL blacklist mode

### ISSUE THREAD

**Issue by sknorr** [andy-portmen/open-in#24]
My use case is this: I need two web applications that only run in Chrome. I want to use Firefox for everything else.

Hence, what I'd like to have is a domain/URL blacklist (for the two applications that I genuinely want to run in Chrome) and the option to open everything else in Firefox. Would that be in the cards?

**Comment by GuilloOme** [comment]
like #6, no?

**Comment by sknorr** [comment]
Ah thanks, that's basically the same issue! Sorry for the dupe.
