### ISSUE TITLE
Open in chrome in chrome web store

### ISSUE THREAD

**Issue by S-T-S** [andy-portmen/open-in#26]
As Edge based on Chromium can install extensions from the chrome web store, having Open in Chrome available for Edge is now requested.

**Comment by haukeFCE** [comment]
Same for the brave and chromium web browsers! 

As a workaround just use the chromium extension and change the path in settings to Google Chrome.

**Comment by andy-portmen** [comment]
Use my "External Application Button" extension.

**Comment by appel** [comment]
@andy-portmen First of, thank you for this set of extensions, they are super helpful!

I am using a heavily modified Vivaldi (via extensions and a user stylesheet) as an alternative to [Ferdium](https://github.com/ferdium/ferdium-app). It contains vertical tabs with my most used platforms, e.g. Gmail, Google Chat, Messages, Whatsapp, Messenger, and others. I'm also using Chrome for web dev work and Edge for personal stuff.

The Open in Edge extension allows me to set Ctrl + click to open links from Vivaldi directly in Edge. I would love to be able to set up Alt + click to send links from Vivaldi to Chrome.

I've tried the External Application Button extension as per your suggestion, which works fine via the context menu, but unfortunately it is missing the "Open With Keyboard-Mouse-Click Combinations" feature. The workaround @ghost suggested is better in that sense (and is what I'm currently using), but ideally "Open in Chrome" would also be available in the Chrome extension store for the other Chromium based browsers (Edge, Brave, Vivaldi, etc).
