### ISSUE TITLE
sharepoint querystring with & and OR

### ISSUE THREAD

**Issue by josy1024** [andy-portmen/open-in#28]
this link does not work with "openin" on sharepoint office 365
the extension should strip out everything after ? 

sharepoint online.

from https://tenant.sharepoint.com/sites/sc/docs/filename.pdf?CT=1559559014624&OR=ItemsView

to:
https://tenant.sharepoint.com/sites/sc/docs/filename.pdf

**Comment by andy-portmen** [comment]
Since it is hard to support query modifications per hostname, create a middle-man batch file that receives the URL from this extension and alters it the way you need.
