### ISSUE TITLE
Can we get this to open in FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by robjac** [andy-portmen/open-in#29]
I'd like the Chrome extenstion to be able to open in FirefoxDeveloperEdition. I think this would be a welcome addition to many users/developers. The script could fallback to developer edition if firefox is not found.

**Comment by jpinnix** [comment]
Same, but for Google Chrome Canary, Firefox Nightly, Safari Technology Preview.

**Comment by andy-portmen** [comment]
Just go to the options page and set the correct path. Alternatively use my "External Application Button" extension
