### ISSUE TITLE
Can you create a open in Photoshop

### ISSUE THREAD

**Issue by goselito** [andy-portmen/open-in#30]
Would it be possible to create an open in photoshop extension? I believe a lot of people will find this helpful as the extension available in the chrome store does not work.

**Comment by andy-portmen** [comment]
my chrome store account is full. If anybody can open a new one, we can add this one too.

**Comment by goselito** [comment]
How do I go about opening a chrome store account?

**Comment by andy-portmen** [comment]
You need to activate the developer mode; https://chrome.google.com/webstore/developer/dashboard. note that there is 5$ fee. If you plan to do so, please use a fresh email address that can be shared with me.
