### ISSUE TITLE
Add support for Brave browser

### ISSUE THREAD

**Issue by ElijahLynn** [andy-portmen/open-in#31]
Would like support for "Open in Brave browser".

**Comment by andy-portmen** [comment]
see https://github.com/andy-portmen/open-in/issues/30

**Comment by ElijahLynn** [comment]
Ah, interesting thanks.

**Comment by ElijahLynn** [comment]
Maybe the extension could be configurable in the settings on which "open in <app>" can be used/configured? Then it could just be one extension.

**Comment by andy-portmen** [comment]
You can do this with my "External Application Button" extension.

**Comment by ElijahLynn** [comment]
Thanks will check that in a bit.

**Comment by andy-portmen** [comment]
https://chrome.google.com/webstore/detail/open-in-brave-browser/mgmnomlncpmfgelhofilonnecmbdaoia
https://addons.mozilla.org/firefox/addon/open-in-brave-browser/
