### ISSUE TITLE
Feature Request: Blacklist websites/domains for Open With Left-Click

### ISSUE THREAD

**Issue by e-t-l** [andy-portmen/open-in#34]
I posted an issue recently where I described how I use Firefox for all websites except Gmail, for which I use Chrome. I've set up the Open-In extension so that left-clicking all links defaults to open-in FF. However, if I'm navigating within Gmail, I'd like to stay in the window I'm in. I'd like the ability to blacklist **https://mail.google.com/*/** so that left-clicking gmail links would open them in the current browser, not in Firefox.

**Comment by markstos** [comment]
Is this different than the "Reverse Mode" feature? I'm using it like you describe, but with Fastmail.

**Comment by e-t-l** [comment]
Thanks, didn't see the Reverse Mode feature. That should solve my issue; closing this thread.
