### ISSUE TITLE
RFI: Managed Storage

### ISSUE THREAD

**Issue by Mixxaz** [andy-portmen/open-in#36]
Hi @andy-portmen 

This is just a request for information. My question.

Using 'Managed Storage', will the extension detect the opening of the url and redirect it to the correct browser.

> ex. I type in www.bing.com in my Chrome browser and press enter to load the website. The extension is configured using Managed Storage to redirect www.bing.com to Internet Explorer. Because of this the extensions detects the url and moves it to the correct browser.

Thanks for your support. I see a great use case in your extensions.

**Comment by andy-portmen** [comment]
Have you seen https://www.chromium.org/administrators/configuring-policy-for-extensions

**Comment by Mixxaz** [comment]
Yes I've seen it but on Windows it is not so straightforward.

Would the registry entries be something like this:
[HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\3rdparty\extensions\<ExtensionID>\policy\hosts\ and then host1, host2, ... + the same for urls

or how would this work?

Also to me it is important that it is automatic when the policy is configured.

Thanks

**Comment by andy-portmen** [comment]
![Screen Shot 2019-11-29 at 1 24 07 PM](https://user-images.githubusercontent.com/6779535/69871934-fc4f8980-12ab-11ea-8675-d0f0d26c25c4.png)

**Comment by andy-portmen** [comment]
To check all policies, go to `chrome://policy`. You can also open the background page from `chrome://extensions` and use `chrome.storage.managed.get(null, p => console.log(p))` to see all the policies that are configured for this extension.

> Also to me it is important that it is automatic when the policy is configured.

I know it is doable, but I am not a Windows user so you need to figure it out yourself.

**Comment by Mixxaz** [comment]
Thanks for the info.

I'll check out if it works automatically. 

> Also to me it is important that it is automatic when the policy is configured.
> I know it is doable, but I am not a Windows user so you need to figure it out yourself.
I'll check it out but would have guessed that the extension takes care of checking the URL and redirecting correctly when necessary.

Thanks for the quick support. I'm going to keep it open to report back but I'm not foreseeing issues.

**Comment by Mixxaz** [comment]
Hi,

Tried and the policy seems to detect the settings correctly but not applied.
Also tried the left click settings and they seem to not work as well. 
My setting should open the below in IE when clicking the link:
![image](https://user-images.githubusercontent.com/58254786/69875007-c9fa5800-12bc-11ea-9926-4c6fe5c7fd04.png)

However when clicking the link in google it doesn't work:
![image](https://user-images.githubusercontent.com/58254786/69875038-db436480-12bc-11ea-95e3-8e73afe19568.png)

And they should even be pushed automatically with the policy:
![image](https://user-images.githubusercontent.com/58254786/69875218-0037d780-12bd-11ea-9b55-e6f4da7982c0.png)

You have any ideas why it only opens when pressing the extension?

**Comment by andy-portmen** [comment]
Note that local settings overwrite the policy ones. So if you have both, the local ones are supposed to get applied.

> However when clicking the link in google it doesn't work:

I tested on Google with the same local preference and it works for me. For now, try to use bing.com instead of Google to see if it works or not. Google might have used a new redirecting URL. If so we should handle them; https://github.com/andy-portmen/open-in/blob/master/common/data/inject.js#L50

> And they should even be pushed automatically with the policy:

Your policy pref should be `www.gva.be`

**Comment by Mixxaz** [comment]
Ok so I adapted the policy pref but when using google.com the link is not being redirected to the different browser.
When using Bing.com it is being redirected.

I tried using both Bing and Google as search provider in the address bar but both are unable to send the user to the correct browser automatically. <-- Is this another event listener you need to implement?

**Comment by andy-portmen** [comment]
can you figure out the new redirecting URL. You need to use the "Inspect" context menu item over the link element.
