### ISSUE TITLE
Feature request - Add "Open in chromium" extension

### ISSUE THREAD

**Issue by GuilloOme** [andy-portmen/open-in#4]
The only difference with "open in chrome" is the execution path and the icon.

**Comment by GuilloOme** [comment]
A possible work-around is setting a custom path in the options of the "open in chrome" extension.

**Comment by RogueScholar** [comment]
Just wanted to echo the need for this extension, and to highlight that it is desperately and quite ironically needed in the Chrome Web Store most of all, thanks to the growing popularity of Vivaldi Browser which shares the CWS. As you might have guessed, I myself am a Vivaldi devotee, and for the rare instances when a site insists on receiving a Chrome user agent string I'd much rather just have an Open in Chrome extension button/context menu entry than mess with one of the UA string customizers.

Thank you for all the great tools you make to ease our journey through the interwebs.

**Comment by andy-portmen** [comment]
> A possible work-around is setting a custom path in the options of the "open in chrome" extension.

You could also use my external application button too. Anyhow we now have open-in-chromium too

https://chrome.google.com/webstore/detail/open-in-chromium-browser/bhfenhhfpcpkknkahnlogooiodcofkjl
https://addons.mozilla.org/en-US/firefox/addon/open-in-chromium-browser

Opera version is still under review.
