### ISSUE TITLE
Feature Request: Only Open Links inside DOM Element

### ISSUE THREAD

**Issue by jesse9212** [andy-portmen/open-in#41]
This extension has trouble with sites like gmail and messenger because some of the internal navigation links (clicking on different conversations or emails) will open in new tabs instead of just links in the email body or links people post in various messengers.

**Comment by gardmkdg1** [comment]
https://guides.github.com/feed/index.xml

**Comment by andy-portmen** [comment]
Please reopen after the next release if you still have the issue
