### ISSUE TITLE
Does not work in Mac OS Catalina

### ISSUE THREAD

**Issue by vivekojha85** [andy-portmen/open-in#44]
I installed the script and also checked the connection,still when I open the URL in extension it gives me this error:
<img width="421" alt="Screen Shot 2020-07-09 at 4 08 59 PM" src="https://user-images.githubusercontent.com/5068230/87086039-eb320800-c1fe-11ea-809b-8c4fe4acf18b.png">

Here is the screenshot from my native client test
<img width="850" alt="Screen Shot 2020-07-09 at 4 12 36 PM" src="https://user-images.githubusercontent.com/5068230/87086112-0e5cb780-c1ff-11ea-9ad1-7b976fb73ef7.png">

**Comment by andy-portmen** [comment]
It means that the extension cannot find the "Explorer" executable. Mac OS does not have IE browser, so you cannot use this product on a Mac computer.

P.S. You can change the name of the executable on the options page to a browser that is already installed on your OS.
