### ISSUE TITLE
URLs option seems dead for Open in IE

### ISSUE THREAD

**Issue by pvickrey** [andy-portmen/open-in#46]
When attempting to use URLs for Open in IE across computers the URL function doesn't seem to work, regardless if the URL is in Registry Keys or in the Options menu.
Switching to Open in Edge and it seems to work in both locations (Registry Keys or Options menu).

I'm testing the same URL in both extensions, testing on the same machines.

**Comment by andy-portmen** [comment]
Please reopen if you still have the issue
