### ISSUE TITLE
Feature request - add possibility to whitelist domain for left click

### ISSUE THREAD

**Issue by GuilloOme** [andy-portmen/open-in#6]
Instead of opening only the listed domain in another browser, it would be nice to be able to say: anything that is NOT in this domain list -> Open in Xxxx

## Usecase
I use 2 browsers to isolate my "casual" browsing from my "logged-in" browsing:
- logged in a chromium for my gmail/facebook/github/reddit/slack/anythingRequireToBeLoggedIn 
- browsing in a more secure Firefox where my cookies are destroyed on close

Many times a day, I receive a link to an article or a kitten video that I don't want to open in the current context. 

So it would be nice that on left/normal click on links, anythings that is not a domain I trust/want -> open it in this other browser.

**Comment by steffix73h** [comment]
#2

**Comment by andy-portmen** [comment]
There will be a reverse mode option in the left-click section of the options page. Since redirecting all links is tricky please give it a test and report if there are issues. We are going to have this on "Open in Chrome" extension for now.

**Comment by markstos** [comment]
I want to say "Thanks" for the "Reverse Mode" feature and explain how I use.  I see the feature has been available for about a year now-- I wonder if it's time to remove the "experimental" label.

I want to use Firefox for most of my browsing but on Linux Chrome has a great feature that Firefox does not.  Chrome allows you to create an "app" from any website using "More Tool... / Create Shortcut / Open in New Window".   Once created, the an icon appears for the app in the launcher and the app can be launched separately from the browser and will appear with no browser URL bar or tabs-- for the most part it works like it's own app.

For example, this is great for treating "Fastmail" or "Gmail" as it's own app. It's also useful for other sites you might like to treat as an "app", like Jira, Slack, Google Calendar or Spotify.

Normally external links in these "apps" open in a new, normal Chrome window that belongs to the same profile as an app.

By using this extension and "Reverse Mode", I'm able to whitelist the URLs that belong to the "app" and open external links in Firefox. Once done, it feels irrelevant that the "app" is implemented with Chrome.

This feature may also be of interest to people who using memory hogging Electron apps like Spotify or Slack. Now they can run in existing browser without installing another huge copy of the Chromium project.

To take it a step further, I want my personal email "app" to open links in a personal Firefox profile and my work email "app" to open in a work Firefox profile.

To handle this, I created two Firefox profiles. The each have their own `.desktop` file with a custom icon. They are launched with custom "WM_CLASS" as well. In this way the window manager also treats it like have two completely unique Firefox apps, although there is only one install. 

Here's a "work" Firefox .desktop file I added to ~/.local/share/applications/firefox-work.desktop:

```
[Desktop Entry]
Version=1.0
Name=AmigoFox
GenericName=Work Firefox Browser
Comment=Browse the World Wide Web
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=/usr/lib/firefox/firefox -P RideAmigos --class firefox-work %u
Icon=firefox-symbolic
Terminal=false
X-MultipleArgs=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;
StartupNotify=true
StartupWMClass=firefox-work
Categories=Network;WebBrowser;
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=New Window
Exec=/usr/lib/firefox/firefox -P Work --class firefox-work --new-window %u

[Desktop Action new-private-window]
Name=New Private Window
Exec=/usr/lib/firefox/firefox -P Work --class firefox-work --private-window %u
```
Notice the Icon has been changed to `firefox-symbolic` which is an alternate icon that allows me to tell apart the two profiles. 

Finally, it seems this app requires calling a single executable on the command line with no arguments, so I added a new bash script in `~/.local/share/bin/firefox-work`

```
#!/usr/bin/bash
/usr/bin/firefox -P Work --class firefox-work "$1"
```

Putting the pieces together I can have a "Work email app" (running in Chrome) that opens links in "Work Firefox".

**Comment by andy-portmen** [comment]
@markstos thanks for sharing. I am going to migrate your instrcution to the FAQs page. btw, you may look at my "External Application Button" extension if you need to pass arguments.

**Comment by beyond9thousand** [comment]
> I want to say "Thanks" for the "Reverse Mode" feature and explain how I use. I see the feature has been available for about a year now-- I wonder if it's time to remove the "experimental" label.
> 
> [moved to the FAQs page](https://add0n.com/open-in.html?nc#faq24)

I tried multiple things and it just won't work for me, the website i am trying to whitelist is discord. what should i be entering in each of the 3 fields while having reverse mode enabled?
![image](https://user-images.githubusercontent.com/77363063/200696156-ec0c48f0-8334-408f-a605-4d6adea74193.png)

**Comment by akuntsch** [comment]
> > I want to say "Thanks" for the "Reverse Mode" feature and explain how I use. I see the feature has been available for about a year now-- I wonder if it's time to remove the "experimental" label.
> > [moved to the FAQs page](https://add0n.com/open-in.html?nc#faq24)
> 
> I tried multiple things and it just won't work for me, the website i am trying to whitelist is discord. what should i be entering in each of the 3 fields while having reverse mode enabled? ![image](https://user-images.githubusercontent.com/77363063/200696156-ec0c48f0-8334-408f-a605-4d6adea74193.png)

Same here.  @beyond9thousand Did you get it to work somehow?

EDIT: Never mind. Works after copying the native messaging host to the correct directory (on Linux and Microsoft edge it's not `~/.config/microsoftedge` but `~/.config/microsoft-edge`) and restarting the browser.

**Comment by beyond9thousand** [comment]
That wasn't my issue at all. It was working if i don't require any blacklisting.

**Comment by rEnr3n** [comment]
@beyond9thousand It works only if you left-click a link that contains discord.com. Typing/pasting a discord link on the omnibar won't work. Middle/right clicking a link won't work either.

**Comment by beliaev-maksim** [comment]
thanks for the feature, I use it like to exclude domains and provide a URL pattern:
`*://(.*)domain.io/*`

that allows to filter things like:
https://my.domain.io
https://domain.io
https://my.domain.io/64648


to add support for queries as well:
`*://(.*)domain.io/(.*)\?{*}?`
