### ISSUE TITLE
How to uninstall this NodeJS ?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [andy-portmen/open-in#63]
How to uninstall this NodeJS ?
---
Open In - Open page in selected Browser.
Open current page or link in another browser
https://add0n.com/open-in.html

**Comment by andy-portmen** [comment]
Download the ZIP package for your OS. Then run uninstaller script.

**Comment by Clemens-Ratte-Polle** [comment]
ok, thanks :)
I used it with this Addon:
Open In - Open page in selected Browser.
Open current page or link in another browser
https://add0n.com/open-in.html
