### ISSUE TITLE
cannot match address with question mark ? in URL (pattern matching with URL pattern)

### ISSUE THREAD

**Issue by capi1O** [andy-portmen/open-in#81]
I use this extension in reverse mode in order to open all links in Firefox except the links on one domain, using a pattern in "Open with Left-Click" > "Comma-separated list of URLs".

It works except for URLs that contain a question mark (URL with query parameters), ex. https://www.domain.com/foo?bar=1

Here are the patterns I tried:

- `https://www.domain.com/(.*)`
- `https://www.domain.com/(.*\?.*)`
- `https://www.domain.com/([\/a-zA-Z\d\?=]*)`

I read the [URL pattern doc](https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API) but I think this is an issue with the extension.

**Comment by capsudo** [comment]
Sorry wrong repo, I opened an issue on the correct one here => https://github.com/andy-portmen/open-in-firefox/issues/2
