### ISSUE TITLE
Client successfully installed, but still not detected by the Chromium extension: "Specified native messaging host not found."

### ISSUE THREAD

**Issue by vctls** [andy-portmen/open-in#82]
I followed the installation instructions, the client was successfully installed with my existing NodeJS install, but the extension still doesn't see it. I get this error in the console:
> Specified native messaging host not found.

How can I debug this issue?

Chromium 113
Ubuntu 22.04
Gnome 42.5
X11

Firefox path correctly set in the options.

Client installer output:
```
./linux/install.sh 
/usr/bin/node
NodeJS status = 0
Installer is using your system NodeJS.

 -> Root directory is /home/victor/.config
 -> Creating a directory at /home/victor/.config/google-chrome/NativeMessagingHosts
 -> Chrome Browser is supported
 -> Creating a directory at /home/victor/.config/chromium/NativeMessagingHosts
 -> Chromium Browser is supported
 -> Creating a directory at /home/victor/.config/vivaldi/NativeMessagingHosts
 -> Vivaldi Browser is supported
 -> Creating a directory at /home/victor/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts
 -> Brave Browser is supported
 -> Creating a directory at /home/victor/.config/microsoftedge/NativeMessagingHosts
 -> Microsoft Edge Browser is supported
 -> Creating a directory at /home/victor/.mozilla/native-messaging-hosts
 -> Firefox Browser is supported
 -> Creating a directory at /home/victor/.waterfox/native-messaging-hosts
 -> Waterfox Browser is supported
 -> Creating a directory at /home/victor/.tor-browser/app/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts
 -> Tor Browser is supported
 -> Creating a directory at /home/victor/.thunderbird/native-messaging-hosts
 -> Thunderbird Email Client is supported
 -> Creating a directory at /home/victor/.config/com.add0n.node
 => Native Host is installed in /home/victor/.config/com.add0n.node

>>> host is ready <<<
```

**Comment by alanhsieh4444** [comment]
I have the same issue but with some different configuration, anyone could figure out the problem?

I am also using Ubuntu 22.04 but with wayland (sway) and firefox (115.0.2), I don't have NodeJS, thus, using embedded NodeJS.

Following messages are firefox console logs

AbortError: Native application start canceled by user NativeMessaging.sys.mjs:178
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsINativeMessagingPortal.closeSession] NativeMessaging.sys.mjs:361

**Comment by vctls** [comment]
Found the problem in my case. It was simply because my Chromium installation is not using the default config directory. I had already tried copying the `com.add0n.node.json` file to its config directory, but messed up the path in the process.  
Corrected the path, fixed.
@alanhsieh4444 you may want to open another issue if you problem is still present.
