### ISSUE TITLE
not able to use "open in" in Vivaldi browser

### ISSUE THREAD

**Issue by hernaniturpin** [andy-portmen/open-in#86]
I installed the "Open in Chromium" addon on vivaldi browser and I've set the "Path to the executable" to "open -a "Google Chrome" in mac os. But nothing happens when I press the link. I know that the nodeJS client is installed correctly because I can use the extension in chrome browser (for open in firefox for example). 
What can I do to make it work on Vivaldi browser?
My goal is to open links in google chrome from Vivaldi browser

**Comment by andy-portmen** [comment]
On macOS, you need to put the app name, not the `open ...` command. So replace the command with `Google Chrome`
