### ISSUE TITLE
Always force domains to open in external browser, even when not a clicked link? (solves redirects)

### ISSUE THREAD

**Issue by e-t-l** [andy-portmen/open-in#97]
If I have "example.com" set as a domain to open with left-click, there are two common situations where it will NOT open in the external browser:
1. Navigating to "example.com" directly from the address bar
2. Clicking a redirect link, e.g. "bit.ly/etc", which then redirects to example.com

Would it be possible to include an option to **always force certain domains to open in external browser, no matter what what**?

**Comment by andy-portmen** [comment]
"Open in Firefox" now includes this feature. You can define hostnames on the options page and it redirects to the external browser at network level so that your current browser is not handling the response anymore.

**Comment by andy-portmen** [comment]
version 0.4.5
